### ISSUE TITLE
Upozornění u komentářů

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/OneMozilla-MozillaCZ#4]
Napadlo mne přesunout umístění upozornění týkající se komentářů na trochu agresivnější místo. Nyní je [pod formulářem](https://github.com/MozillaCZ/OneMozilla-MozillaCZ/blob/master/comments.php#L89), ale i tak se objevují komentáře s dotazy na podporu.

Nebylo by viditelnější nad formulářem, případně alespoň zdůraznit "Pokud se chcete na něco zeptat, použijte diskuzní fórum"? Třeba `<strong>`? Co myslíš, @JasnaPaka ?

**Comment by JasnaPaka** [comment]
Souhlasím.

**Comment by MikkCZ** [comment]
Navrhuji tedy přesun pod nadpis "Přidejte svůj komentář", změnit `použijte diskuzní fórum` na `navštivte naše fórum podpory` a vytučnění.

**Comment by MikkCZ** [comment]
Nasazeno.
