### ISSUE TITLE
Novější ikonu Windows na stránku ke stažení

### ISSUE THREAD

**Issue by MikkCZ** [MozillaCZ/OneMozilla-MozillaCZ#43]
XP už je dost stará https://www.mozilla.cz/stahnout/firefox/

**Comment by vasimi** [comment]
Nahodil bych tam rovnou SVG ikony, ať to vypadá dobře na všech displejích. Teď tam vidím kostičky.

**Comment by MikkCZ** [comment]
Postahoval jsem SVG pro Windows, OS X, Android i iOS, ale Linux mi dělá problémy. Tak malá ikonka by nemusela mít 50 kB. Dokázal bys najít nějakou menší verzi?

**Comment by MikkCZ** [comment]
Uvažuji o úplném předělání stránky pro stažení stylem https://fedoraproject.org/wiki/Join/cs#P.C5.99ipojte_se_ke_komunit.C4.9B_Fedory_a_p.C5.99isp.C4.9Bjte - ikony v "dlaždicích". Nebudeš @MekliCZ někdy v Praze, že bychom si nad tím sedli? Ikony bychom mohli použít vlastní nebo něco jako na https://www.mozilla.org/en-US/firefox/all/#cs.

**Comment by vasimi** [comment]
@MikkCZ Do Prahy jedu zítra, ale čas budu mít jen večer (+ cca hodinu v sobotu).

**Comment by MikkCZ** [comment]
[icons.zip](https://github.com/MozillaCZ/OneMozilla-MozillaCZ/files/644808/icons.zip) - SVG Android, Apple, OS X El Capitan, Tux, Windows 10
