### ISSUE TITLE
Obrázek v boxíku podpory nemá stejné pozadí jako stránka (bílá vs šedá)

### ISSUE THREAD

**Issue by zelitomas** [MozillaCZ/OneMozilla-MozillaCZ#46]
![screenshot-2017-5-30 mozilla cz](https://cloud.githubusercontent.com/assets/3105674/26574183/ad17688e-4520-11e7-8237-d9fc87011bc5.png)

Příště raději PNG :)

**Comment by zelitomas** [comment]
![snimek z 2017-05-30 10-20-18](https://cloud.githubusercontent.com/assets/3105674/26574502/e5596ab6-4521-11e7-896b-a75ad185050e.png)

To samé platí pro draka v článcích

**Comment by MikkCZ** [comment]
Tohle možná není chyba šablony, ale pozadí některých obrázků, které jsou nahrané přímo na FTP.

**Comment by MikkCZ** [comment]
Opraveno.
