### ISSUE TITLE
Špatně vypadající tlačítko pro stažení Firefoxu při nižším rozlišení

### ISSUE THREAD

**Issue by zelitomas** [MozillaCZ/OneMozilla-MozillaCZ#50]
Viz screenshot:
![snimek obrazovky 2017-11-23 v 00 06 38](https://user-images.githubusercontent.com/3105674/33153511-676c3812-cfe2-11e7-804e-5b30dd60e74d.png)

Pořízeno při velikosti 900 x 480 px.

**Comment by MikkCZ** [comment]
Tohle by mělo fungovat i po tom, co zase odmažeme slovo Quantum.
```
.download-button .download-link .download-content {
  background-size: 5em;
}
```
